---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: "{{ project_name }}"
  name: deny-by-default
spec:
  podSelector:
  ingress: []

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: "{{ project_name }}"
  name: allow-same-namespace
spec:
  podSelector:
  ingress:
  - from:
    - podSelector: {}
---
kind: NetworkPolicy
apiVersion: extensions/v1beta1
metadata:
  namespace: "{{ project_name }}"
  name: allow-from-default-namespace
spec:
  podSelector:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default

