{
 "title": "Kubernetes Container Utilization (no filter)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "v_project", "label": "Project", "query": "${VAR_V_PROJECT}" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_cpu_usage_seconds_total[5m])) / scalar(sum(machine_cpu_cores))",
     "legendFormat": "{{ '{{ pod_name }}' }}"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) / sum(machine_cpu_cores)",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes) by (pod_name)",
     "legendFormat": "{{ '{{ pod_name }}' }}"
    },
    {
     "expr": "sum(container_memory_working_set_bytes)",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_reads_total[5m]))",
     "legendFormat": "{{ '{{ pod_name }}' }}"
    },
    {
     "expr": "sum(rate(container_fs_reads_total[5m]))",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_fs_writes_total[5m]))",
     "legendFormat": "{{ '{{ pod_name }}' }}"
    },
    {
     "expr": "sum(rate(container_fs_writes_total[5m]))",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Network Rx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_receive_bytes_total[5m]))",
     "legendFormat": "{{ '{{ pod_name }}' }}"
    },
    {
     "expr": "sum(rate(container_network_receive_bytes_total[5m]))",
     "legendFormat": "_Total"
    }
   ]
  },
  {
   "title": "Network Tx",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name) (rate(container_network_transmit_bytes_total[5m]))",
     "legendFormat": "{{ '{{ pod_name }}' }}"
    },
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[5m]))",
     "legendFormat": "_Total"
    }
   ]
  }
 ]
}